# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDip-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DDip-iOS
  pod 'Moya', '~> 14.0'
  pod 'Then'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 6.0'
end
